using System.Collections.Generic;
using Anything.UI.Avalonia.Settings;

namespace Anything.UI.Avalonia;

public static class Lang
{
    private static readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["en-US"] = new()
        {
            ["AppTitle"] = "Anything",
            ["SearchFiles"] = "Search files...",
            ["Settings"] = "Settings",
            ["FoundResults"] = "Found: {0} results",
            ["Cancel"] = "Cancel",
            ["Save"] = "Save",
            ["Skip"] = "Skip",
            ["GetStarted"] = "Get Started",
            ["WelcomeTitle"] = "Welcome to Anything",
            ["WelcomeSubtitle"] = "Let's get you set up quickly",
            ["ChooseTheme"] = "Choose your theme:",
            ["Language"] = "Language:",
            ["Theme"] = "Theme:",
            ["MaxResults"] = "Max search results:",
            ["Close"] = "Close",
            ["Minimize"] = "Minimize",
            ["Maximize"] = "Maximize",
            ["Dark"] = "Dark",
            ["Light"] = "Light",
            ["Search"] = "Search",
            ["Filters"] = "Filters",
            ["MatchCase"] = "Match case",
            ["WholeWord"] = "Whole word",
            ["MatchPath"] = "Match path",
            ["Regex"] = "Regex",
            ["Type"] = "Type:",
            ["All"] = "All",
            ["Files"] = "Files",
            ["Folders"] = "Folders",
            ["MinSize"] = "Min size:",
            ["MaxSize"] = "Max size:",
            ["Bytes"] = "bytes",
            ["Indexer"] = "Indexer",
            ["EnableIndexer"] = "Enable background file indexer",
            ["IndexerAutoStart"] = "Auto-start indexer on boot",
            ["IndexPath"] = "Index path:",
            ["IndexerStatus"] = "Indexer status:",
            ["IndexerRunning"] = "Running",
            ["IndexerStopped"] = "Stopped",
        },
        ["ru-RU"] = new()
        {
            ["AppTitle"] = "Anything",
            ["SearchFiles"] = "Поиск файлов...",
            ["Settings"] = "Настройки",
            ["FoundResults"] = "Найдено: {0} результатов",
            ["Cancel"] = "Отмена",
            ["Save"] = "Сохранить",
            ["Skip"] = "Пропустить",
            ["GetStarted"] = "Начать",
            ["WelcomeTitle"] = "Добро пожаловать в Anything",
            ["WelcomeSubtitle"] = "Давайте быстро настроимся",
            ["ChooseTheme"] = "Выберите тему:",
            ["Language"] = "Язык:",
            ["Theme"] = "Тема:",
            ["MaxResults"] = "Макс. результатов:",
            ["Close"] = "Закрыть",
            ["Minimize"] = "Свернуть",
            ["Maximize"] = "Развернуть",
            ["Dark"] = "Тёмная",
            ["Light"] = "Светлая",
            ["Search"] = "Поиск",
            ["Filters"] = "Фильтры",
            ["MatchCase"] = "Учитывать регистр",
            ["WholeWord"] = "Целое слово",
            ["MatchPath"] = "Искать в пути",
            ["Regex"] = "Регулярка",
            ["Type"] = "Тип:",
            ["All"] = "Все",
            ["Files"] = "Файлы",
            ["Folders"] = "Папки",
            ["MinSize"] = "Мин. размер:",
            ["MaxSize"] = "Макс. размер:",
            ["Bytes"] = "байт",
            ["Indexer"] = "Индексатор",
            ["EnableIndexer"] = "Включить фоновый индексатор",
            ["IndexerAutoStart"] = "Автозапуск индексатора при загрузке",
            ["IndexPath"] = "Путь индексации:",
            ["IndexerStatus"] = "Статус индексатора:",
            ["IndexerRunning"] = "Работает",
            ["IndexerStopped"] = "Остановлен",
        },
        ["de-DE"] = new()
        {
            ["AppTitle"] = "Anything",
            ["SearchFiles"] = "Dateien durchsuchen...",
            ["Settings"] = "Einstellungen",
            ["FoundResults"] = "Gefunden: {0} Ergebnisse",
            ["Cancel"] = "Abbrechen",
            ["Save"] = "Speichern",
            ["Skip"] = "Überspringen",
            ["GetStarted"] = "Loslegen",
            ["WelcomeTitle"] = "Willkommen bei Anything",
            ["WelcomeSubtitle"] = "Schnelle Einrichtung",
            ["ChooseTheme"] = "Wählen Sie ein Thema:",
            ["Language"] = "Sprache:",
            ["Theme"] = "Design:",
            ["MaxResults"] = "Max. Ergebnisse:",
            ["Close"] = "Schließen",
            ["Minimize"] = "Minimieren",
            ["Maximize"] = "Maximieren",
            ["Dark"] = "Dunkel",
            ["Light"] = "Hell",
            ["Search"] = "Suche",
            ["Filters"] = "Filter",
            ["MatchCase"] = "Groß-/Kleinschreibung",
            ["WholeWord"] = "Ganzes Wort",
            ["MatchPath"] = "Pfad durchsuchen",
            ["Regex"] = "Regex",
            ["Type"] = "Typ:",
            ["All"] = "Alle",
            ["Files"] = "Dateien",
            ["Folders"] = "Ordner",
            ["MinSize"] = "Min. Größe:",
            ["MaxSize"] = "Max. Größe:",
            ["Bytes"] = "Bytes",
            ["Indexer"] = "Indexierer",
            ["EnableIndexer"] = "Hintergrundindexierer aktivieren",
            ["IndexerAutoStart"] = "Indexierer automatisch starten",
            ["IndexPath"] = "Indexpfad:",
            ["IndexerStatus"] = "Status:",
            ["IndexerRunning"] = "Läuft",
            ["IndexerStopped"] = "Gestoppt",
        },
        ["fr-FR"] = new()
        {
            ["AppTitle"] = "Anything",
            ["SearchFiles"] = "Rechercher des fichiers...",
            ["Settings"] = "Paramètres",
            ["FoundResults"] = "Trouvé: {0} résultats",
            ["Cancel"] = "Annuler",
            ["Save"] = "Enregistrer",
            ["Skip"] = "Passer",
            ["GetStarted"] = "Commencer",
            ["WelcomeTitle"] = "Bienvenue dans Anything",
            ["WelcomeSubtitle"] = "Configuration rapide",
            ["ChooseTheme"] = "Choisissez un thème:",
            ["Language"] = "Langue:",
            ["Theme"] = "Thème:",
            ["MaxResults"] = "Résultats max:",
            ["Close"] = "Fermer",
            ["Minimize"] = "Minimiser",
            ["Maximize"] = "Maximiser",
            ["Dark"] = "Sombre",
            ["Light"] = "Clair",
            ["Search"] = "Recherche",
            ["Filters"] = "Filtres",
            ["MatchCase"] = "Respecter la casse",
            ["WholeWord"] = "Mot entier",
            ["MatchPath"] = "Chercher dans le chemin",
            ["Regex"] = "Regex",
            ["Type"] = "Type:",
            ["All"] = "Tout",
            ["Files"] = "Fichiers",
            ["Folders"] = "Dossiers",
            ["MinSize"] = "Taille min:",
            ["MaxSize"] = "Taille max:",
            ["Bytes"] = "octets",
            ["Indexer"] = "Indexeur",
            ["EnableIndexer"] = "Activer l'indexeur en arrière-plan",
            ["IndexerAutoStart"] = "Démarrage automatique",
            ["IndexPath"] = "Chemin d'indexation:",
            ["IndexerStatus"] = "Statut:",
            ["IndexerRunning"] = "En cours",
            ["IndexerStopped"] = "Arrêté",
        },
        ["es-ES"] = new()
        {
            ["AppTitle"] = "Anything",
            ["SearchFiles"] = "Buscar archivos...",
            ["Settings"] = "Ajustes",
            ["FoundResults"] = "Encontrado: {0} resultados",
            ["Cancel"] = "Cancelar",
            ["Save"] = "Guardar",
            ["Skip"] = "Saltar",
            ["GetStarted"] = "Comenzar",
            ["WelcomeTitle"] = "Bienvenido a Anything",
            ["WelcomeSubtitle"] = "Configuración rápida",
            ["ChooseTheme"] = "Elige un tema:",
            ["Language"] = "Idioma:",
            ["Theme"] = "Tema:",
            ["MaxResults"] = "Resultados máx:",
            ["Close"] = "Cerrar",
            ["Minimize"] = "Minimizar",
            ["Maximize"] = "Maximizar",
            ["Dark"] = "Oscuro",
            ["Light"] = "Claro",
            ["Search"] = "Buscar",
            ["Filters"] = "Filtros",
            ["MatchCase"] = "Coincidir mayúsculas",
            ["WholeWord"] = "Palabra completa",
            ["MatchPath"] = "Buscar en ruta",
            ["Regex"] = "Regex",
            ["Type"] = "Tipo:",
            ["All"] = "Todo",
            ["Files"] = "Archivos",
            ["Folders"] = "Carpetas",
            ["MinSize"] = "Tamaño min:",
            ["MaxSize"] = "Tamaño máx:",
            ["Bytes"] = "bytes",
            ["Indexer"] = "Indexador",
            ["EnableIndexer"] = "Activar indexador en segundo plano",
            ["IndexerAutoStart"] = "Inicio automático",
            ["IndexPath"] = "Ruta de indexación:",
            ["IndexerStatus"] = "Estado:",
            ["IndexerRunning"] = "Ejecutando",
            ["IndexerStopped"] = "Detenido",
        },
        ["zh-CN"] = new()
        {
            ["AppTitle"] = "Anything",
            ["SearchFiles"] = "搜索文件...",
            ["Settings"] = "设置",
            ["FoundResults"] = "找到: {0} 个结果",
            ["Cancel"] = "取消",
            ["Save"] = "保存",
            ["Skip"] = "跳过",
            ["GetStarted"] = "开始使用",
            ["WelcomeTitle"] = "欢迎使用 Anything",
            ["WelcomeSubtitle"] = "快速设置",
            ["ChooseTheme"] = "选择主题:",
            ["Language"] = "语言:",
            ["Theme"] = "主题:",
            ["MaxResults"] = "最大结果数:",
            ["Close"] = "关闭",
            ["Minimize"] = "最小化",
            ["Maximize"] = "最大化",
            ["Dark"] = "深色",
            ["Light"] = "浅色",
            ["Search"] = "搜索",
            ["Filters"] = "筛选",
            ["MatchCase"] = "区分大小写",
            ["WholeWord"] = "全词匹配",
            ["MatchPath"] = "搜索路径",
            ["Regex"] = "正则",
            ["Type"] = "类型:",
            ["All"] = "全部",
            ["Files"] = "文件",
            ["Folders"] = "文件夹",
            ["MinSize"] = "最小大小:",
            ["MaxSize"] = "最大大小:",
            ["Bytes"] = "字节",
            ["Indexer"] = "索引器",
            ["EnableIndexer"] = "启用后台文件索引器",
            ["IndexerAutoStart"] = "开机自动启动索引器",
            ["IndexPath"] = "索引路径:",
            ["IndexerStatus"] = "索引器状态:",
            ["IndexerRunning"] = "运行中",
            ["IndexerStopped"] = "已停止",
        },
        ["ja-JP"] = new()
        {
            ["AppTitle"] = "Anything",
            ["SearchFiles"] = "ファイルを検索...",
            ["Settings"] = "設定",
            ["FoundResults"] = "見つかりました: {0} 件",
            ["Cancel"] = "キャンセル",
            ["Save"] = "保存",
            ["Skip"] = "スキップ",
            ["GetStarted"] = "始める",
            ["WelcomeTitle"] = "Anything へようこそ",
            ["WelcomeSubtitle"] = "クイックセットアップ",
            ["ChooseTheme"] = "テーマを選択:",
            ["Language"] = "言語:",
            ["Theme"] = "テーマ:",
            ["MaxResults"] = "最大結果数:",
            ["Close"] = "閉じる",
            ["Minimize"] = "最小化",
            ["Maximize"] = "最大化",
            ["Dark"] = "ダーク",
            ["Light"] = "ライト",
            ["Search"] = "検索",
            ["Filters"] = "フィルター",
            ["MatchCase"] = "大文字と小文字を区別",
            ["WholeWord"] = "単語全体",
            ["MatchPath"] = "パスを検索",
            ["Regex"] = "正規表現",
            ["Type"] = "種類:",
            ["All"] = "すべて",
            ["Files"] = "ファイル",
            ["Folders"] = "フォルダー",
            ["MinSize"] = "最小サイズ:",
            ["MaxSize"] = "最大サイズ:",
            ["Bytes"] = "バイト",
            ["Indexer"] = "インデクサー",
            ["EnableIndexer"] = "バックグラウンドインデクサーを有効化",
            ["IndexerAutoStart"] = "起動時に自動開始",
            ["IndexPath"] = "インデックスパス:",
            ["IndexerStatus"] = "ステータス:",
            ["IndexerRunning"] = "実行中",
            ["IndexerStopped"] = "停止中",
        },
    };

    public static string T(string key)
    {
        var lang = SettingsManager.Current.Language;
        if (_strings.TryGetValue(lang, out var dict) && dict.TryGetValue(key, out var val))
            return val;
        if (_strings["en-US"].TryGetValue(key, out var fallback))
            return fallback;
        return key;
    }
}